### ISSUE TITLE
Sito web 

### ISSUE THREAD

**Issue by Pedro-Leonii** [ALT-F4-eng/SorgentiDocumentazione#80]
- [ ] Cambio nome repo documenti compilati
- [x] Sviluppo sito

**Comment by guirongLan** [comment]
Sviluppato il sito web
- creato index.html
- creato cartella Asset per depositare file accessori
- creato cartella e file CSS per desktop e mobile
- creato cartella e file JAVASCRIPT per ritornare da top del sito web e per navigazione smartphone 
- cambiato nome di primi verbali esterni il quale la data non combacia all'istruzione interno di norme di progetto
- creato github pages
Da controllare nel altro repo
- [ ] se è accettabile fare il merge sul ramo main ?
Dubbio
- che nome cambiare la repo?
